package com.gene.sphere.geneservice.model;

import lombok.Data;

import javax.persistence.*;

/**
 * JPA entity representing a gene and associated clinical/research metadata.
 * <p>
 * Lombok's {@link Data} annotation generates getters, setters, equals, hashCode, and toString.
 * Persisted via {@link Entity}.
 * </p>
 */
@Data
@Entity
@Table(name="genes")
public class Gene {

    /**
     * Surrogate primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * Gene symbol/name (e.g., "TP53", "EGFR").
     */
    @Column(nullable=false, unique=true)
    private String name;

    /**
     * Human-readable description or summary of the gene.
     */
    @Column(length=2000)
    private String description;

    /**
     * The normal biological function/role of the gene.
     */
    private String normalFunction;

    /**
     * Known or typical effects of pathogenic variants/mutations in this gene.
     */
    private String mutationEffect;

    /**
     * Shows how common is a gene mutation in lung cancer
     */
    private String prevalence;

    /**
     * Relevant or approved therapies (e.g., targeted drugs) associated with this gene/mutations.
     */
    private String therapies;

    /**
     * References or URLs to research articles, databases, or guidelines.
     */
    private String researchLinks;

}